on: [ "push", "pull_request" ]

name: "Run tests"

jobs:
  nix:
    name: "Run tests *nix / all awks"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, macos-11.0, macos-12, macos-13 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          # key: ${{ runner.os }}-soft
          key: ${{ matrix.os }}-soft--all--2

      - name: "run tests"
        run: |
          ./makesure tested_awks tested_json_suite

  win:
    name: "Run tests Win"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache-soft
        with:
          path: soft
          key: ${{ matrix.os }}-soft--win--2

      - name: "run tests"
        run: |
          & bash -e -c "./makesure"
